# Generated by Django 5.2.8 on 2025-11-11 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_student_photo_teacher_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teachers_nid',
            new_name='teacher_nid',
        ),
        migrations.RemoveField(
            model_name='class',
            name='section',
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100)),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.class')),
            ],
        ),
    ]
