# Generated by Django 5.2.8 on 2025-11-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_rename_teachers_nid_teacher_teacher_nid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_serial',
            field=models.SmallIntegerField(default=0, max_length=2),
        ),
    ]
