# Generated by Django 5.2.8 on 2025-11-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_class_class_serial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('exam_type', 'subject', 'class_ref', 'academic_year')},
        ),
        migrations.AlterField(
            model_name='exam',
            name='academic_year',
            field=models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=2025),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('MIDTERM', 'Mid-Term Exam'), ('FINAL', 'Final Exam'), ('FIRST_CLASS_TEST', 'Class Test One'), ('SECOND_CLASS_TEST', 'Class Test Two'), ('PRACTICAL', 'Practical Exam')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_name',
        ),
    ]
