# Generated by Django 5.2.8 on 2025-11-21 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_student_gender_student_permanent_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='portal.section'),
        ),
    ]
