# Generated by Django 5.2.8 on 2025-11-21 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_enrollment_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='roll_number',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='roll_number',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_serial',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='section',
            name='class_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='portal.class'),
        ),
    ]
