# Generated by Django 5.2.8 on 2025-11-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_remove_student_roll_number_enrollment_roll_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, choices=[('ISL', 'Islam'), ('CHR', 'Christian'), ('HIN', 'Hindu'), ('BUD', 'Buddhist'), ('OTH', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='religion',
            field=models.CharField(blank=True, choices=[('ISL', 'Islam'), ('CHR', 'Christian'), ('HIN', 'Hindu'), ('BUD', 'Buddhist'), ('OTH', 'Other')], max_length=10, null=True),
        ),
    ]
